# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4f58edb94712475f620a8168f518f1f7d0267e6bb78651cc2f85fe325ed24c3df93e2294dce5045266b6fc361d6ced6caeec19cacabf439788e6a5fde74cba01

test:
  secret_key_base: a16ff9828237f7197e6c3728d09779c7e577014b88d798b50940f98dd2fbae3e1d6b901137838fdb5d04e64262f5615132a1e06ca9f5fc71c2f82b7bab0abd6e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
