require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe HeroesController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Hero. As you add validations to Hero, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    {
      name: "SuperHero",
      internal_name: "SuperHero",
      classification: "Warrior"
    }
  }

  let(:invalid_attributes) {
    {
      name: nil,
      internal_name: nil,
      classification: nil
    }
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # HeroesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    login_user

    it "assigns all heroes as @heroes" do
      hero = Hero.create! valid_attributes
      get :index, params: {}, session: valid_session
      expect(assigns(:heroes)).to eq([hero])
    end
  end

  describe "GET #show" do
    login_user

    it "assigns the requested hero as @hero" do
      hero = Hero.create! valid_attributes
      get :show, params: {id: hero.to_param}, session: valid_session
      expect(assigns(:hero)).to eq(hero)
    end
  end

  describe "GET #new" do
    login_user

    it "assigns a new hero as @hero" do
      get :new, params: {}, session: valid_session
      expect(assigns(:hero)).to be_a_new(Hero)
    end
  end

  describe "GET #edit" do
    login_user

    it "assigns the requested hero as @hero" do
      hero = Hero.create! valid_attributes
      get :edit, params: {id: hero.to_param}, session: valid_session
      expect(assigns(:hero)).to eq(hero)
    end
  end

  describe "POST #create" do
    login_user

    context "with valid params" do
      it "creates a new Hero" do
        expect {
          post :create, params: {hero: valid_attributes}, session: valid_session
        }.to change(Hero, :count).by(1)
      end

      it "assigns a newly created hero as @hero" do
        post :create, params: {hero: valid_attributes}, session: valid_session
        expect(assigns(:hero)).to be_a(Hero)
        expect(assigns(:hero)).to be_persisted
      end

      it "redirects to the created hero" do
        post :create, params: {hero: valid_attributes}, session: valid_session
        expect(response).to redirect_to(Hero.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved hero as @hero" do
        post :create, params: {hero: invalid_attributes}, session: valid_session
        expect(assigns(:hero)).to be_a_new(Hero)
      end

      it "re-renders the 'new' template" do
        post :create, params: {hero: invalid_attributes}, session: valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    login_admin

    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested hero" do
        hero = Hero.create! valid_attributes
        put :update, params: {id: hero.to_param, hero: new_attributes}, session: valid_session
        hero.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested hero as @hero" do
        hero = Hero.create! valid_attributes
        put :update, params: {id: hero.to_param, hero: valid_attributes}, session: valid_session
        expect(assigns(:hero)).to eq(hero)
      end

      it "redirects to the hero" do
        hero = Hero.create! valid_attributes
        put :update, params: {id: hero.to_param, hero: valid_attributes}, session: valid_session
        expect(response).to redirect_to(hero)
      end
    end

    context "with invalid params" do
      it "assigns the hero as @hero" do
        hero = Hero.create! valid_attributes
        put :update, params: {id: hero.to_param, hero: invalid_attributes}, session: valid_session
        expect(assigns(:hero)).to eq(hero)
      end

      it "re-renders the 'edit' template" do
        hero = Hero.create! valid_attributes
        put :update, params: {id: hero.to_param, hero: invalid_attributes}, session: valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    login_user

    it "destroys the requested hero" do
      hero = Hero.create! valid_attributes
      expect {
        delete :destroy, params: {id: hero.to_param}, session: valid_session
      }.to change(Hero, :count).by(-1)
    end

    it "redirects to the heroes list" do
      hero = Hero.create! valid_attributes
      delete :destroy, params: {id: hero.to_param}, session: valid_session
      expect(response).to redirect_to(heroes_url)
    end
  end

end
