require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe ManagersController, type: :controller do
  # FIXME
  login_admin

  # This should return the minimal set of attributes required to create a valid
  # Manager. As you add validations to Manager, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    {
      user_id: User.first.id
    }
  }

  let(:invalid_attributes) {
    {
      user_id: nil
    }
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ManagersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all managers as @managers" do
      manager = Manager.create! valid_attributes
      get :index, params: {}, session: valid_session
      expect(assigns(:managers)).to include(manager)
    end
  end

  describe "GET #show" do
    it "assigns the requested manager as @manager" do
      manager = Manager.create! valid_attributes
      get :show, params: {id: manager.to_param}, session: valid_session
      expect(assigns(:manager)).to eq(manager)
    end
  end

  describe "GET #new" do
    it "assigns a new manager as @manager" do
      get :new, params: {}, session: valid_session
      expect(assigns(:manager)).to be_a_new(Manager)
    end
  end

  describe "GET #edit" do
    it "assigns the requested manager as @manager" do
      manager = Manager.create! valid_attributes
      get :edit, params: {id: manager.to_param}, session: valid_session
      expect(assigns(:manager)).to eq(manager)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Manager" do
        expect {
          post :create, params: {manager: valid_attributes}, session: valid_session
        }.to change(Manager, :count).by(1)
      end

      it "assigns a newly created manager as @manager" do
        post :create, params: {manager: valid_attributes}, session: valid_session
        expect(assigns(:manager)).to be_a(Manager)
        expect(assigns(:manager)).to be_persisted
      end

      it "redirects to the created manager" do
        post :create, params: {manager: valid_attributes}, session: valid_session
        expect(response).to redirect_to(Manager.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved manager as @manager" do
        post :create, params: {manager: invalid_attributes}, session: valid_session
        expect(assigns(:manager)).to be_a_new(Manager)
      end

      it "re-renders the 'new' template" do
        post :create, params: {manager: invalid_attributes}, session: valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested manager" do
        manager = Manager.create! valid_attributes
        put :update, params: {id: manager.to_param, manager: new_attributes}, session: valid_session
        manager.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested manager as @manager" do
        manager = Manager.create! valid_attributes
        put :update, params: {id: manager.to_param, manager: valid_attributes}, session: valid_session
        expect(assigns(:manager)).to eq(manager)
      end

      it "redirects to the manager" do
        manager = Manager.create! valid_attributes
        put :update, params: {id: manager.to_param, manager: valid_attributes}, session: valid_session
        expect(response).to redirect_to(manager)
      end
    end

    context "with invalid params" do
      it "assigns the manager as @manager" do
        manager = Manager.create! valid_attributes
        put :update, params: {id: manager.to_param, manager: invalid_attributes}, session: valid_session
        expect(assigns(:manager)).to eq(manager)
      end

      it "re-renders the 'edit' template" do
        manager = Manager.create! valid_attributes
        put :update, params: {id: manager.to_param, manager: invalid_attributes}, session: valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested manager" do
      manager = Manager.create! valid_attributes
      expect {
        delete :destroy, params: {id: manager.to_param}, session: valid_session
      }.to change(Manager, :count).by(-1)
    end

    it "redirects to the managers list" do
      manager = Manager.create! valid_attributes
      delete :destroy, params: {id: manager.to_param}, session: valid_session
      expect(response).to redirect_to(managers_url)
    end
  end

end
